[project]
name = "sentence-transformers_deployment"
version = "0.1.0"
description = "Deployment for gemma 300m embedding model, using sentence transformers."
requires-python = ">=3.13"
dependencies = [
    "sentence-transformers==5.2.*"
]
